### ISSUE TITLE
[Suggestion] Needs an appsettings.json.example file

### ISSUE THREAD

**Issue by gcarreno** [mr-highball/yt-indexer#1]
Hey mr-highball(@mr-highball),

Could you please drop a `appsettings.json.example` file somewhere in the repository?
Many thanks in advance :smile: !!

This way we can just edit that one instead of trying to guess what the format is :stuck_out_tongue: .

I guess you get a pass on this one since your alcohol level kinda impaired your judgement :stuck_out_tongue_winking_eye: 

Cheers,
Gus
<hr>
P.S.: I like being first poster, LOL!!

**Comment by mr-highball** [comment]
donezo

**Comment by gcarreno** [comment]
Hey mr-highball(@mr-highball),

That's a guddun :wink: !! 

Cheers,
Gus
